default_platform(:android)

platform :android do
  desc "Deploy to internal testing track"
  lane :internal do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "..",
    )

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Deploy to production"
  lane :release do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "..",
    )

    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      metadata_path: "./fastlane/metadata/android",
    )
  end
end
